on:
    push:

permissions:
    actions: write
    
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - run: npm i jsverify
        - run: node code.test.js